describe("editar perfil",()=>{
    it("editar perfil",()=>{
        cy.visit("http://127.0.0.1:8000/")
        cy.get('.icono-nav').click()
        cy.get('#id_username').type("usuario@admin.com")
        cy.get('#id_password').type("contraseña")
        cy.get('.btn').click()
        cy.get('.btn > .nav-link > .icono-nav').click()
        cy.get('.dropstart > .dropdown-menu > :nth-child(1) > .dropdown-item').click()
        cy.get('#id_username').type("vale")
        cy.get('#id_nombres').type("Valeria")
        cy.get('#id_apellidos').type("Balmaceda")
        cy.get('#id_dni').type("12345678")
        cy.get('.form-edit_profile').type("1995-10-23")
        cy.get('#id_direccion').type("36 e/2 y 3 N°2130")
        cy.get('#id_localidad').type("La Plata")
        cy.get('#id_ciudad').type("La Plata")
        cy.get('#id_nacionalidad').type("Argentina")
        cy.get('#id_telefono_1').type("221 1234567")
        cy.get('#id_telefono_2').type("221 9874563")
        cy.get('#id_estado_civil').select(1)
        cy.get('#id_sexo').select(2)
        cy.get('.botones-edituser > .btn').click()        
    })
})