describe("editar usuario", () =>{
    it("", () =>{
        cy.visit("http://127.0.0.1:8000/")
        cy.get('.icono-nav').click()
        cy.get('#id_username').type("usuario@admin.com")
        cy.get('#id_password').type("contraseña")
        cy.get('.btn').click()
        cy.get('#dropdownMenuButton1').click()
        cy.get(':nth-child(2) > .dropdown > .dropdown-menu > :nth-child(1) > .dropdown-item').click()
        cy.get('[href="/edit_user/5"]').click()
        cy.get('#id_username').type("josel")
        cy.get('#id_direccion').type("calle 55")
        cy.get('#id_localidad').type("la plata")
        cy.get('#id_ciudad').type("la Plata")
        cy.get('#id_nacionalidad').type("argentino")
        cy.get('#id_telefono_1').type("5466664")
        cy.get('#id_telefono_2').type("6544644")
        cy.get('#id_estado_civil').select(1)
        cy.get('#id_sexo').select(1)
        cy.get('.botones-edituser > .btn').click()
        cy.get('#dropdownMenuButton1').click()
        cy.get(':nth-child(2) > .dropdown > .dropdown-menu > :nth-child(1) > .dropdown-item').click()
    })
    
})