describe("suite pruebas boton recuperar contraseña", () =>{
    it("", () =>{
        cy.visit("http://127.0.0.1:8000/")
        cy.get('.icono-nav').click()
        cy.get('#id_username').type("usuario@admin.com")
        cy.get('#id_password').type("contraseña")
        cy.get('.btn').click()
        cy.get('.btn > .nav-link > .icono-nav').click()
        cy.get('.dropstart > .dropdown-menu > :nth-child(2) > .dropdown-item').click()
        cy.get('#id_old_password').type("contraseña")
        cy.get('#id_new_password1').type("admin")
        cy.get('#id_new_password2').type("admin")
        cy.get('.botones-registracion > .btn').click()
        cy.get('.btn > .nav-link > .icono-nav').click()
        cy.get('.dropdown-item > p').click()
        cy.get('.icono-nav').click()
        cy.get('#id_username').type("usuario@admin.com")
        cy.get('#id_password').type("admin")
        cy.get('.btn').click()
        cy.get('.btn').should("not.exist")
    })
})